string = "  Hello world!   "
print(f"string = |{string}|")
print()
print("SOME STRING FUNCTIONS")
print(f"string.lower(): |{string.lower()}|")
print(f"string.upper(): |{string.upper()}|")
print(f"string.title(): |{string.title()}|")
print(f"string.swapcase(): |{string.swapcase()}|")
print()
print(f"string.strip(): |{string.strip()}|")
print(f"string.lstrip(): |{string.lstrip()}|")
print(f"string.rstrip(): |{string.rstrip()}|")
print()
print(f"string.center(30): |{string.center(30)}|")
print(f"string.ljust(30) : |{string.ljust(30)}|")
print(f"string.rjust(30) : |{string.rjust(30)}|")
print()
print(f"string.replace('world', 'COMP1753'): |{string.replace('world', 'COMP1753')}|")
print()

print()
input("Press return to continue ...")
