string = "  Hello world!   "
print(f"string = '{string}'")
print()
print("SOME FUNCTIONS USED ON STRINGS")
print(f"len(string) = {len(string)}")
print(f"max(string) = {max(string)}")
print(f"min(string) = {min(string)}")
print()
print("SOME COMBINATIONS")
print(f"len(string.strip())    = {len(string.strip())}")
print(f"max(string.swapcase()) = {max(string.swapcase())}")
print(f"max(string.title())    = {max(string.title())}")
print()

print()
input("Press return to continue ...")
